name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish x64 ModdingToolkit Full
      run: dotnet publish Run8ModdingToolkit\Run8ModdingToolkit.csproj -c Release -o Run8ModdingToolkitFull --sc -f net6.0 -r win-x64 /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true
    - name: Publish x64 ModdingToolkit Slim
      run: dotnet publish Run8ModdingToolkit\Run8ModdingToolkit.csproj -c Release -o Run8ModdingToolkitSlim --no-self-contained -f net6.0 -r win-x64
    - name: Upload x64 ModdingToolkit Full Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Run8ModdingToolkitFull
        path: Run8ModdingToolkitFull/**
        if-no-files-found: warn
    - name: Upload x64 ModdingToolkit Slim Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Run8ModdingToolkitSlim
        path: Run8ModdingToolkitSlim/**
        if-no-files-found: warn